name: smart_rice_analyser
description: A new Flutter project. 
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: '>=2.19.0 <3.0.0'
# environment:
#   sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter: 
    sdk: flutter
    

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  fluttertoast: ^8.1.2
  tflite: ^1.1.2
  url_launcher: ^6.1.14
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.4.4
  form_builder_file_picker: ^4.0.0
  firebase_auth: ^4.0.2
  shared_preferences: ^2.0.15
  image_network: ^2.5.2
  image_picker: ^1.0.4
  firebase_storage: ^11.0.6
  splash_screen_view: ^3.0.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_rating_bar: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/files/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
