// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgXWDeMT6yar3wMmV2hb478nIoquShGEw',
    appId: '1:612907817291:web:19647cb2c634d0ff36f0ce',
    messagingSenderId: '612907817291',
    projectId: 'smartanalyser-3b4b0',
    authDomain: 'smartanalyser-3b4b0.firebaseapp.com',
    storageBucket: 'smartanalyser-3b4b0.appspot.com',
    measurementId: 'G-T0XKSVB10M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwU29HtGxZL25gU6CKHMTN4W3nu7mhzhg',
    appId: '1:612907817291:android:f78f45351be6eca336f0ce',
    messagingSenderId: '612907817291',
    projectId: 'smartanalyser-3b4b0',
    storageBucket: 'smartanalyser-3b4b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLw-_xT82JHgytbIPg5MS4myl0eaGntVA',
    appId: '1:612907817291:ios:53a795f7e14b577c36f0ce',
    messagingSenderId: '612907817291',
    projectId: 'smartanalyser-3b4b0',
    storageBucket: 'smartanalyser-3b4b0.appspot.com',
    iosBundleId: 'com.example.plasticBagsDetection',
  );
}
